# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Dockerfile for building a manylinux2014 TFDV wheel.

# This docker image is essentially pypa/manylinux2014 + bazel.
# TODO(b/272536553): Update filenames that include manylinux2010.
FROM gcr.io/tfx-oss-public/manylinux2014-bazel:bazel-6.1.0
WORKDIR /build
CMD ["tensorflow_data_validation/tools/docker_build/build_manylinux.sh"]
